apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-config
  namespace: default

data:
  sonar.properties: |
    sonar.forceAuthentication=true
    sonar.security.realm=LDAP
    sonar.web.context=/
